// src/lib/components/home/form/Form.svelte
<script>
	import { enhance } from '$app/forms';
	import { poemState } from '$lib/states/poem.svelte.js';
	import FormButton from '$lib/components/home/form/FormButton.svelte';

	let name = $state('');
	let isDisabled = $derived(name.length < 2);

	const handleSubmit = ({ formElement, cancel }) => {
		// Prevent default submission
		cancel();

		fetch(formElement.action, {
			method: formElement.method,
			headers: {
				'Content-Type': 'text/plain'
			},
			body: name
		}).then(async (response) => {
			// Handle response
			if (response.headers.get('content-type') == 'application/json')
				poemState.poem = await response.json();
			else poemState.poem = await response.text();
		});

		poemState.wasNameSubmited = true;
	};
</script>

<form
	action="/api/poem"
	method="POST"
	use:enhance={handleSubmit}
	class="bg-base-menu dark:bg-base-menu-dark relative flex h-10 w-2/3 max-w-xs justify-end rounded-3xl text-sm shadow transition-all duration-300 ease-in-out md:h-12 md:text-base"
>
	<input
		type="text"
		name="name"
		id="name"
		autocomplete="off"
		placeholder="Name"
		bind:value={name}
		class="text-base-text dark:text-base-text-dark font-base outline-base-text dark:outline-base-text-dark w-full rounded-3xl px-4 antialiased outline-0 focus:outline-1"
	/>
	<button
		type="submit"
		aria-label="submit"
		disabled={isDisabled}
		class=" bg-base-menu dark:bg-base-menu-dark outline-base-text dark:outline-base-text-dark text-base-text dark:text-base-text-dark absolute flex aspect-square h-full items-center justify-center rounded-3xl outline-0 focus:outline-1 disabled:cursor-not-allowed disabled:opacity-50"
	>
		<FormButton {isDisabled} />
	</button>
</form>

// components/home/Form.vue
<script setup lang="ts">
const name = useName();
const isSubmitted = useSubmitted();

const handleSubmit = () => {
  useFetch("/api/name", {
    method: "POST",
    body: { name },
    onRequest() {
      isSubmitted.value = true;
    },
  });
};
</script>

<template>
  <form class="relative flex w-fit flex-col" @submit.prevent="handleSubmit">
    <div
      class="peer h-12 border-b-2 transition-all duration-300 ease-in-out"
      :class="{
        'dark:border-b-[#FBFBFB]': name.length >= 2,
        'dark:border-b-[#FBFBFB]/50': name.length < 2,
        'border-b-[#29292a]': name.length >= 2,
        'border-b-[#29292a]/50': name.length < 2,
      }"
    >
      <input
        id="name"
        v-model="name"
        type="text"
        name="name"
        autoComplete="off"
        class="h-full bg-transparent text-base capitalize outline-none"
      />
      <button
        type="submit"
        aria-label="submit"
        class="h-full dark:fill-[#FBFBFB] fill-[#29292a] px-6 outline-none transition-all duration-300 ease-in-out focus:-translate-y-1 dark:disabled:fill-[#FBFBFB]/50 disabled:fill-[#29292a]/50 disabled:cursor-not-allowed"
        :disabled="name.length < 2"
      >
        <svg
          xmlns="http://www.w3.org/2000/svg"
          class="h-4 w-4"
          viewBox="0 0 16 16"
        >
          <path
            d="M15.9.1a.5.5 0 0 1 0 .6l-5.8 14.5a.8.8 0 0 1-1.3.2l-3.2-5-5-3.2a.8.8 0 0 1 .2-1.3L15.3 0a.5.5 0 0 1 .6.1Zm-9.3 10 2.8 4.3 4.7-11.8zm6.8-8.2L1.6 6.6l4.3 2.8 7.5-7.5Z"
          />
        </svg>
      </button>
    </div>
    <label
      for="name"
      class="absolute transition-all duration-200 ease-in-out peer-focus-within:-top-2 peer-active:-top-2"
      :class="{ '-top-2': name.length != 0, 'top-4': name.length == 0 }"
    >
      Name:
    </label>
  </form>
</template>
