// src/lib/components/home/Title.svelte
<article class="flex flex-col items-center text-center">
	<h1
		class="text-base-text font-base text-6xl font-extrabold leading-[0.9] antialiased transition-all duration-300 ease-in-out sm:text-7xl md:text-8xl lg:text-9xl"
	>
		End Poem
	</h1>
	<h2
		class="text-base-text font-signature text-3xl leading-[0.9] antialiased transition-all duration-300 ease-in-out sm:text-4xl md:text-5xl lg:text-6xl"
	>
		by Julian Gough
	</h2>
</article>

// components/home/Title.vue
<template>
  <header class="text-center">
    <h1 class="text-6xl font-bold sm:text-7xl lg:text-8xl 2xl:text-9xl">
      <strong> End Poem </strong>
    </h1>
    <h2 class="font-['Nothing_You_Could_Do'] text-3xl sm:text-4xl lg:text-5xl 2xl:text-6xl">
      by Julian Gough
    </h2>
  </header>
</template>
